# Generated by Django 4.0.4 on 2022-05-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mods',
            options={'ordering': ['time_create'], 'verbose_name': 'моды', 'verbose_name_plural': 'моды'},
        ),
        migrations.AddField(
            model_name='mods',
            name='slug',
            field=models.SlugField(default=21, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mods',
            name='creator',
            field=models.CharField(max_length=50, verbose_name='создатель'),
        ),
        migrations.AlterField(
            model_name='mods',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='mods',
            name='title',
            field=models.CharField(max_length=50, verbose_name='заголовок'),
        ),
    ]
